# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsp" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "b0e5c3a99bfea6e2e5743f3a341ddaaef91eca42e93a67c1ce974b6035a7bfc3"
      url "https://github.com/meabed/tailscale-proxy/releases/download/v#{version}/tsp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "53c36daa98b11487a6aabad291b79c7902b093e6defff108bee399c7770520e7"
      url "https://github.com/meabed/tailscale-proxy/releases/download/v#{version}/tsp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "74e7423c294af9e430f63cc917c9adfcedc316c7af7ad5d838daa24517ced696"
      url "https://github.com/meabed/tailscale-proxy/releases/download/v#{version}/tsp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "59f374b7ef3354dd80600b776005c518e2ad5ed629f961d51c4aeeccdaf85596"
      url "https://github.com/meabed/tailscale-proxy/releases/download/v#{version}/tsp_linux_arm64.tar.gz"
    end
  end

  name "tsp"
  desc "Discover local dev servers and expose them through Tailscale Serve/Funnel"
  homepage "https://github.com/meabed/tailscale-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tsp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tsp"]
    end
  end

  # No zap stanza required

end
