# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsp" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "7bf8f94d5d94a8966817a1a4de924baf6c84d06458b6cdaa09a0f5d688e74f46"
      url "https://github.com/meabed/tailscale-proxy/releases/download/v#{version}/tsp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e01ab501ee92f907fa223106458a5dbb5f8559404938651c2aba910498ee9dd"
      url "https://github.com/meabed/tailscale-proxy/releases/download/v#{version}/tsp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cda5c45e8de3c2ed0640279c92ca7b660ada1acd958926bfde404aeb3d373209"
      url "https://github.com/meabed/tailscale-proxy/releases/download/v#{version}/tsp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7810f27125c97f6a2115790fba98bd098cee650ec8386767e66c94a68e044ec6"
      url "https://github.com/meabed/tailscale-proxy/releases/download/v#{version}/tsp_linux_arm64.tar.gz"
    end
  end

  name "tsp"
  desc "Discover local dev servers and expose them through Tailscale Serve/Funnel"
  homepage "https://github.com/meabed/tailscale-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tsp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tsp"]
    end
  end

  # No zap stanza required

end
