# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsp" do
  version "1.6.2"

  on_macos do
    on_intel do
      sha256 "3e360cdc5f10c4c5b47567d012af195f3da43970551f61544a0b7376616944d8"
      url "https://github.com/meabed/tailscale-proxy/releases/download/v#{version}/tsp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e9d4548ea4d75b2a580eefb0439ba88d0f1ac13c63b85e383eac226cd34b4229"
      url "https://github.com/meabed/tailscale-proxy/releases/download/v#{version}/tsp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "03949a010491260c3e5012cf77ac6600ec4bb6c40de8fcb38793663099a1c96d"
      url "https://github.com/meabed/tailscale-proxy/releases/download/v#{version}/tsp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5ea0e67641d23ccbc9a0228056de01578c7d1fece63747cd8d25ed1fa0094379"
      url "https://github.com/meabed/tailscale-proxy/releases/download/v#{version}/tsp_linux_arm64.tar.gz"
    end
  end

  name "tsp"
  desc "Discover local dev servers and expose them through Tailscale Serve/Funnel"
  homepage "https://github.com/meabed/tailscale-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tsp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tsp"]
    end
  end

  # No zap stanza required

end
